package com.code93.linkcoop.persistence.models

import android.os.Parcelable
import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.parcelize.Parcelize

@Parcelize
@Entity()
data class FieldsTrx(
        @PrimaryKey(autoGenerate = true)
        val id: Int = 0,
        var bitmap: String = "",
        var message_code: String = "",
        var transaction_code: String = "",
        var reference: String = "",
        var account_number: String = "",
        var primary_account: String = "",
        var secondary_account: String = "",
        var transaction_amount: String = "",
        var debit_amount: String = "",
        var credit_amount: String = "",
        var reversal_credit_amount: String = "",
        var reversal_debit_amount: String = "",
        var commision_amount: String = "",
        var supercargo_amount: String = "",
        var taxe_iva: String = "",
        var taxe_isa: String = "",
        var taxe_isd: String = "",
        var taxe_rte: String = "",
        var other_taxe: String = "",
        var other_amount: String = "",
        var ledger_balance: String = "",
        var available_balance: String = "",
        var business_date: String = "",
        var switch_date_time: String = "",
        var adquirer_date_time: String = "",
        var device_date_time: String = "",
        var issuer_date_time: String = "",
        var limit_date: String = "",
        var switch_sequence: String = "",
        var adquirer_sequence: String = "",
        var device_sequence: String = "",
        var adquirer_region: String = "",
        var adquirer_county: String = "",
        var adquirer_city: String = "",
        var issuer_institution_id: String = "",
        var adquirer_institution_id: String = "",
        var terminal_id: String = "",
        var operator_id: String = "",
        var supervisor_id: String = "",
        var branch_id: String = "",
        var terminal_location: String = "",
        var channel_id: String = "",
        var reversal_indicator: String = "",
        var service_code: String = "",
        var authorization_code: String = "",
        var response_code: String = "",
        var currency_code: String = "",
        var issuer_institution_number: String = "",
        var adquirer_institution_number: String = "",
        var record_names: String = "",
        var source_names: String = "",
        var target_names: String = "",
        var phone_number: String = "",
        var card_info: String = "",
        var original_data: String = "",
        var buffer_data: String = "",
        var security_data: String = "",
        var token_data: String = "",
        var product_id: String = "",
        var email_address: String = "",
        var acct_type: String = "",
        var user_id: String = "",
        var password: String = "",
        var emv_data: String = "",
        var validator_data: String = "",
) : Parcelable {}